subdir_files = \
   giella-shared/common/src/filters/convert_to_flags-CmpNP-tags.regex \
   giella-shared/common/src/filters/extract-OLang_ENG-strings.regex \
   giella-shared/common/src/filters/extract-OLang_FIN-strings.regex \
   giella-shared/common/src/filters/extract-OLang_NNO-strings.regex \
   giella-shared/common/src/filters/extract-OLang_NOB-strings.regex \
   giella-shared/common/src/filters/extract-OLang_SME-strings.regex \
   giella-shared/common/src/filters/extract-OLang_SWE-strings.regex \
   giella-shared/common/src/filters/extract-Sem_Plc-strings.regex \
   giella-shared/common/src/filters/make-optional-NGminip-tags.regex \
   giella-shared/common/src/filters/make-optional-adv_comp-tags.regex \
   giella-shared/common/src/filters/make-optional-homonymy-tags.regex \
   giella-shared/common/src/filters/make-optional-hyph-tags.regex \
   giella-shared/common/src/filters/make-optional-transitivity-tags.regex \
   giella-shared/common/src/filters/make-optional-v1-tags.regex \
   giella-shared/common/src/filters/make-optional-variant-tags.regex \
   giella-shared/common/src/filters/remove-ABBR-strings.regex \
   giella-shared/common/src/filters/remove-ACR-strings.regex \
   giella-shared/common/src/filters/remove-CLB-strings.regex \
   giella-shared/common/src/filters/remove-MT-strings.regex \
   giella-shared/common/src/filters/remove-MinusSpell-strings.regex \
   giella-shared/common/src/filters/remove-NA-strings.regex \
   giella-shared/common/src/filters/remove-NG-strings.regex \
   giella-shared/common/src/filters/remove-NGminip-strings.regex \
   giella-shared/common/src/filters/remove-OLang_ENG-strings.regex \
   giella-shared/common/src/filters/remove-OLang_FIN-strings.regex \
   giella-shared/common/src/filters/remove-OLang_NNO-strings.regex \
   giella-shared/common/src/filters/remove-OLang_NOB-strings.regex \
   giella-shared/common/src/filters/remove-OLang_SME-strings.regex \
   giella-shared/common/src/filters/remove-OLang_SWE-strings.regex \
   giella-shared/common/src/filters/remove-OLang_UND-strings.regex \
   giella-shared/common/src/filters/remove-Orth_IPA-strings.regex \
   giella-shared/common/src/filters/remove-Orth_Strd-strings.regex \
   giella-shared/common/src/filters/remove-PUNCT-strings.regex \
   giella-shared/common/src/filters/remove-Prop-strings.regex \
   giella-shared/common/src/filters/remove-RCmpnd-strings.regex \
   giella-shared/common/src/filters/remove-UseCirc-strings.regex \
   giella-shared/common/src/filters/remove-adv_comp-tags.regex \
   giella-shared/common/src/filters/remove-derivation-position-tags.regex \
   giella-shared/common/src/filters/remove-homonymy-tags.regex \
   giella-shared/common/src/filters/remove-hyphenated-strings.regex \
   giella-shared/common/src/filters/remove-hyphenation-marks.regex \
   giella-shared/common/src/filters/remove-infl_boundary-marks.regex \
   giella-shared/common/src/filters/remove-infl_deriv-borders.regex \
   giella-shared/common/src/filters/remove-mwe-strings.regex \
   giella-shared/common/src/filters/remove-mwe-tags.regex \
   giella-shared/common/src/filters/remove-nonfirst_infl_boundary-marks.regex \
   giella-shared/common/src/filters/remove-norm-comp-tags.regex \
   giella-shared/common/src/filters/remove-number-string-tags.regex \
   giella-shared/common/src/filters/remove-orig_lang-tags.regex \
   giella-shared/common/src/filters/remove-orthography-tags.regex \
   giella-shared/common/src/filters/remove-transitivity-tags.regex \
   giella-shared/common/src/filters/remove-usage-tags.regex \
   giella-shared/common/src/filters/remove-usage_except_NGminip-tags.regex \
   giella-shared/common/src/filters/remove-usage_except_speller-tags.regex \
   giella-shared/common/src/filters/remove-use_marg-strings.regex \
   giella-shared/common/src/filters/remove-variant-strings.regex \
   giella-shared/common/src/filters/remove-variant-tags.regex \
   giella-shared/common/src/filters/remove-word-boundary.regex \
   giella-shared/common/src/filters/reorder-subpos-tags.regex \
   giella-shared/common/src/filters/split-CmpNP-tags.regex \
   giella-shared/common/src/filters/tag-lowercase_error-strings.regex \
   giella-shared/common/tools/spellcheckers/fstbased/filters/convert_to_flags-CmpN-tags.regex \
   giella-shared/common/tools/spellcheckers/fstbased/filters/split-CmpN-tags.regex \
   giella-shared/common/tools/spellcheckers/listbased/filters/extract-RCmpnd-strings.regex \
   giella-shared/smi/src/morphology/stems/smi-propernouns.lexc \
   giella-shared/smi/src/morphology/stems/webadresses.lexc \
   giella-shared/smi/src/syntax/dependency.cg3 \
   giella-shared/smi/src/syntax/functions.cg3 \
   giella-shared/smi/src/syntax/konteaksta.cg3 \
   giella-shared/smi/src/syntax/korp.cg3 \
   giella-shared/urj-Cyrl/src/morphology/stems/urj-Cyrl-propernouns.lexc
