internalName: __UND___keyboard

locales:
  en:
    name: &bundleName "__UNDEFINED__ Keyboard"
    description: "A mobile OS keyboard for __UNDEFINED__ from the Divvun group at UiT."
  nb:
    name: "__UNDEFINED__ tastatur"
    description: "Et mobiltastatur for __UNDEFINED__ fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga árktalaš universitehta
email: feedback@divvun.no

layouts: [__UND__]

version: 1.0
build: 1

targets:
  android:
    packageId: no.divvun.keyboards.__UND__
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sami_keyboard

  ios:
    packageId: no.divvun.keyboards.__UND__
    bundleName: *bundleName
