# This template merge lang-config file should be stored in
# .gut/ of each language repo. It contains:
# - template: url of template repo
# - rev_id: automatically maintained
# - template_sha: sha of last known version merged with this language
# - replacements: list of string replacements: placeholder -> real string
template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 1
template_sha = "ddbc686883b2f2ed66bf312a52fd109cc8144450"

[replacements]
__UND__ = 
__UND2C__ = 
__UNDEFINED__ = 
