#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
GIELLA_CORE=$THISDIR/..

# Wrong usage - short instruction:
if ! test $# -eq 1 ; then
    echo
    echo "Usage: $0 LANGUAGE_CODE (ISO 639 code, all variants, all codes)"
    echo
    exit 1
fi

Language=$(${GIELLA_CORE}/scripts/iso639-to-name.sh $1)

if [ ! -z "$Language" ]; then
   echo
   echo The ISO 639 code \"$1\" is used for $Language
   echo
fi
