internalName: __COLLECTION___keyboard

locales:
  en:
    name: &bundleName "__COLLECTION__ Keyboards"
    description: "Mobile OS keyboards for __COLLECTION__ languages from the Divvun group at UiT."
  nb:
    name: "__COLLECTION__ tastatur"
    description: "Mobiltastatur for __COLLECTION__ fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2016 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [__UND__]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.__COLLECTION__
    icon: sami-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.__COLLECTION__
    bundleName: *bundleName
    icon:
        90: sami-icon-small.png
        150: sami-icon.png
  osx: *AppleID
